### ISSUE TITLE
Provide licence information

### ISSUE THREAD

**Issue by vanakenm** [interactive-apps/dhis2-touch#15]
The project as is does not provide any licence information. This make it difficult/impossible to use in most company context as it means it is 100% copyright from the authors (despite being publicly available).

Could you provide a licence (ideally a "known" one such as MIT/GPL/Apache so that what can be done or not with the provided software would be clear).

Thanks & congrats for the great work.

**Comment by chingalo** [comment]
Hello @vanakenm,
 
Thanks for getting a look on our app, we have added a licence.
