### ISSUE TITLE
Custom form does not respect disable property

### ISSUE THREAD

**Issue by rajey** [interactive-apps/dhis2-touch#31]
Even if the input may be disabled in the design. Custom form does not respect that

Quick observation is that custom form codes saved by DHIS2 put disable attribute as `disabled="true/". Perhaps custom form in mobile fail to read the trailing slash

**Comment by chingalo** [comment]
I have checked it, it was true. It was introduced during support of programs rules for custom forms for events. But we have resolved it. Kindly checkout lasted release of the app or using the lastest app on google play store
